### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by delbertlegg** [SCODEMeetup/mofb-api#20]
Integrate with Travis CI to run tests on push and deploy to GCP on merge.

**Comment by vijayyadav06** [comment]
Once you open a PR you can see the travis ci build running.
![image](https://user-images.githubusercontent.com/1335655/52908244-ab503680-323f-11e9-9ff8-6bd8cbec1845.png)

Once the build finishes the PR is ready to be reviewed.
![image](https://user-images.githubusercontent.com/1335655/52908246-b014ea80-323f-11e9-8d17-5cebce3c6cc2.png)
