### ISSUE TITLE
Create API endpoint to return all services under Food (showing all successors).

### ISSUE THREAD

**Issue by vijayyadav06** [SCODEMeetup/mofb-api#27]
This is needed to display all filters under food. Right now its only showing the first level children

**Comment by delbertlegg** [comment]
You should be able to accomplish this by calling `/children` on the first level children under food (so it will call it if the category is expanded). Will that work, or are we intending on showing all subcategories of food as one level below food?

**Comment by vijayyadav06** [comment]
You are right, displaying all successors (covering multiple levels below food). This could be done simply by hardcoding(with id's) as well if iterating datasets via query sounds crazy. We can hardcode them in UI as well. knowing breakable changes coming in April/May onwards.   
![image](https://user-images.githubusercontent.com/1335655/52903209-2dad0c00-31e8-11e9-8853-b9b6ee6dc0bc.png)

**Comment by delbertlegg** [comment]
Closed with #31
