### ISSUE TITLE
Get HandOnCentral data refreshed.

### ISSUE THREAD

**Issue by vijayyadav06** [SCODEMeetup/mofb-api#54]
Continue to follow up with Mackenzie who is reaching out to HandOnCentral Ohio to refresh the data.

Mackenzie King  [6 days ago]
Received an email from HandsOn today– Tiffany Wright CEO of HandsOn is aligning with her team and will get back to us by end of week. There has been some staff turnover in the org this past year, but she would like to update the data. We're eager to support her

**Comment by mycarrysun** [comment]
This is done and we have a new dataset online
